name: bw
pauseCountdown: 60
gameTime: 3600
world: world
pos1: 86.1203695398217;-15.514944207540506;-102.9890381555217;37.663246;-13.615916
pos2: -72.9127697559265;68.46838823171544;113.56125224291112;-135.58704;25.83408
specSpawn: 8.481968680039602;32.0;9.498098947576645;125.554565;60.15
lobbySpawn: 9.193192448447741;48.0;4.8930970023444305;102.61206;-22.765963
lobbySpawnWorld: world
minPlayers: 2
postGameWaiting: 3
teams:
  Red:
    isNewColor: true
    color: RED
    maxPlayers: 8
    bed: 7.0;18.0;-60.0;0.0;0.0
    spawn: 8.578831516517514;18.0;-77.33030218205333;4.2943115;16.384848
    actualName: Red
  Blue:
    isNewColor: true
    color: LIGHT_BLUE
    maxPlayers: 8
    bed: 11.0;18.0;78.0;0.0;0.0
    spawn: 11.286070169558439;18.0;97.9058907610792;179.0426;18.90004
    actualName: Blue
spawners:
- maxSpawnedResources: -1
  hologramEnabled: true
  location: 13.769528890250468;14.0;-56.10429799826586;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: iron
- maxSpawnedResources: -1
  hologramEnabled: true
  location: -29.15636748734935;18.0;-14.807388107252185;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: gold
- maxSpawnedResources: -1
  hologramEnabled: true
  location: 47.803836004239166;18.0;-16.49772244586914;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: gold
- maxSpawnedResources: -1
  hologramEnabled: true
  location: 48.67775429323774;18.0;35.436554244952156;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: gold
- maxSpawnedResources: -1
  hologramEnabled: true
  location: -30.618129458465937;18.0;37.111872178814366;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: gold
- maxSpawnedResources: -1
  hologramEnabled: true
  location: 4.466823890164228;14.0;75.21424320056757;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: iron
- maxSpawnedResources: -1
  hologramEnabled: true
  location: 14.513108809671092;14.0;-56.543669276941586;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: bronze
- maxSpawnedResources: -1
  hologramEnabled: true
  location: 32.69999998807907;14.0;-38.66949043065806;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: bronze
- maxSpawnedResources: -1
  hologramEnabled: true
  location: 31.19129147684343;14.0;-38.655548271487376;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: iron
- maxSpawnedResources: -1
  hologramEnabled: true
  location: -13.687928431986442;14.0;-39.30000001192093;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: iron
- maxSpawnedResources: -1
  hologramEnabled: true
  location: -13.69161150633402;14.0;-41.02224748543113;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: bronze
- maxSpawnedResources: -1
  hologramEnabled: true
  location: -13.699999988079071;14.0;57.31926521143623;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: bronze
- maxSpawnedResources: -1
  hologramEnabled: true
  location: -12.633361537211378;14.0;57.30000001192093;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: iron
- maxSpawnedResources: -1
  hologramEnabled: true
  location: 32.69999998807907;14.0;58.30000001192093;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: iron
- maxSpawnedResources: -1
  hologramEnabled: true
  location: 32.69999998807907;14.0;59.59107220976279;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: bronze
- maxSpawnedResources: -1
  hologramEnabled: true
  location: 7.275457867903756;13.0;35.445355742899515;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: gold
- maxSpawnedResources: -1
  hologramEnabled: true
  location: 6.221106123967673;13.0;-15.683677389535543;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: gold
- maxSpawnedResources: -1
  hologramEnabled: true
  location: 51.63043420824113;20.0;-15.481320525408275;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: gold
- maxSpawnedResources: -1
  hologramEnabled: true
  location: 53.212428475009155;22.0;31.8839886853364;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: gold
- maxSpawnedResources: -1
  hologramEnabled: true
  location: -33.8966045864257;22.0;-12.61930745678966;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: gold
- maxSpawnedResources: -1
  hologramEnabled: true
  location: -32.243941664309396;20.0;34.31298074343347;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: gold
- maxSpawnedResources: -1
  hologramEnabled: true
  location: 4.575902533909564;14.0;75.69999998807907;0.0;0.0
  customName: null
  startLevel: 1.0
  team: null
  type: bronze
stores:
- isBaby: 'false'
  loc: 10.699999988079071;14.0;75.69999998807907;174.29315;-3.4499228
  parent: 'false'
  shop: null
  name: §4Barter
  skin: null
  type: VILLAGER
- isBaby: 'false'
  loc: 8.300000011920929;14.0;-56.69999998807907;-4.91923;22.199677
  parent: 'false'
  shop: null
  name: §a§lVillager_shop
  skin: null
  type: VILLAGER
constant:
  compass-enabled: inherit
  add-wool-to-inventory-on-join: inherit
  in-lobby-colored-leather-by-team: inherit
  allow-crafting: inherit
  join-randomly-after-lobby-timeout: inherit
  join-randomly-on-lobby-join: inherit
  keep-inventory-on-death: inherit
  prevent-killing-villagers: inherit
  player-drops: inherit
  friendlyfire: inherit
  lobbybossbar: inherit
  bossbar: inherit
  lobbyscoreboard: inherit
  scoreboard: inherit
  prevent-spawning-mobs: inherit
  spawner-holograms: inherit
  spawner-disable-merge: inherit
  game-start-items: inherit
  player-respawn-items: inherit
  spawner-holograms-countdown: inherit
  damage-when-player-is-not-in-arena: inherit
  remove-unused-target-blocks: inherit
  allow-block-falling: inherit
  holo-above-bed: inherit
  allow-spectator-join: inherit
  anchor-auto-fill: inherit
  anchor-decreasing: inherit
  cake-target-block-eating: inherit
  target-block-explosions: inherit
arenaTime: WORLD
arenaWeather: default
lobbyBossBarColor: default
gameBossBarColor: default
